apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url:  http://victorialogs:9428
    editable: true
    

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    editable: true