auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 7d # days to delete old logs, you can change
  max_query_lookback: 7d # days to delete old logs, you can change

# ruler:
#   alertmanager_url: http://localhost:9093
# alertmanager_client:
 #   tls_cert_path: /etc/ssl/tls_prometheus_crt.crt
 #   tls_key_path:/etc/ssl/tls_prometheus_key.key
 #   tls_insecure_skip_verify: true
 #   basic_auth_username: $observ_user
 #   basic_auth_password: $observ_passw 

analytics:
  reporting_enabled: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
  
querier:
  query_ingesters_within: 2h # avoid https://github.com/grafana/loki/issues/6043
