auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  chunk_retain_period: 24h

  
storage_config:
  # boltdb_shipper:
  #   active_index_directory: /var/lib/loki/index
  #   cache_location: /var/lib/loki/index_cache
  #   shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/chunks

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
    # - from: 2020-10-24
    #   store: boltdb-shipper
    #   object_store: filesystem
    #   schema: v11
    #   index:
    #     prefix: index_
    #     period: 24h    

limits_config:
  retention_period: 7d # days to delete old logs, you can change
  max_query_lookback: 7d # days to delete old logs, you can change
  # enforce_metric_name: true
  reject_old_samples: true
  reject_old_samples_max_age: 7d

# ruler:
#   alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
  
querier:
  query_ingesters_within: 2h # avoid https://github.com/grafana/loki/issues/6043
