apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    jsonData:
      maxLines: 1000
    basicAuth: false
    url: http://loki:3100
    isDefault: false
    editable: true

  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url:  http://victorialogs:9428
    editable: true

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    editable: true  

  - name: VictoriaMetrics(proxy)
    type: victoriametrics-datasource
    access: proxy
    editable: true  
    url: http://victoriametrics:8428

  - name: VictoriaMetrics-cluster(proxy)
    type: victoriametrics-datasource
    access: proxy
    editable: true  
    url: http://vmauth:8427/select/0/prometheus
